### ISSUE TITLE
`composer.json` should be valid

### ISSUE THREAD

**Issue by llaville** [php-ds/polyfill#105]
Hello,

I know, it's a little error, but current version of `composer.json` is not valid, because it does not satify the [JSON schema](https://github.com/composer/composer/blob/main/res/composer-schema.json) validation !

Package [description](https://getcomposer.org/doc/04-schema.md#description) is missing.

`composer validate` command produced such results

```
./composer.json is valid for simple usage with Composer but has
strict errors that make it unable to be published as a package
See https://getcomposer.org/doc/04-schema.md for details on the schema
# Publish errors
- description : The property description is required
```

**Comment by llaville** [comment]
Free ping, to let know status

**Comment by llaville** [comment]
Is this project still maintained ?

**Comment by rtheunissen** [comment]
Yes it is. I'd like to discontinue the polyfill but this project is active in general. I've been working on a sorted set and some interface changes.

**Comment by theofidry** [comment]
@rtheunissen is there a reason to discontinue the polyfill though? I think increase adoption it's better than a PHP extension (even if there is performance benefits to the latter)

**Comment by rtheunissen** [comment]
It's a tricky problem, but I think if I could do it all over again I wouldn't include the polyfill at all. While it does improve adoption of the library, I'm not convinced that adopting something practically worse is a good thing overall. The effect is antithetical to the goal of this project. Those who want to use it should find a way to install the extension one way or another. 

In other words, the existence of the polyfill discourages adoption of the extension. The problem to solve is to make adoption of the extension either easier, or default. 

I think the ideal solution to the problem that the polyfill is trying to solve is to instead make the library available by default, either by merging with the language or at the distribution level as a default extension.

**Comment by theofidry** [comment]
>I'm not convinced that adopting something practically worse is a good thing overall.

This is only my opinion, but I think this polyfill is a net positive :) Indeed my primary motive to use this library is the features, not the performances.

And while performance definitely matters, if you are concerned or wish to improve them, then the extension is available. As a user it's a freebie so I'll be inclined to do it, but I'll also admit it has been helpful to be able to use it right away thanks to the polyfill way some annoying client third-party hosting provider adds the extension.

But this is purely as a user, since as a maintainer this may be very different...

**Comment by llaville** [comment]
Adding a description to a composer.json file is not the most hard to do, unless you've really decided to abandon this package.
In such case, please mark up using the GitHub repo feature (archive) please !
I won't ask to identify it on packagist because it will need to re-publish a new release with (https://getcomposer.org/doc/04-schema.md#abandoned).
