### ISSUE TITLE
Relevance of tests

### ISSUE THREAD

**Issue by dantudor** [php-ds/polyfill#2]
Hi @rtheunissen,

Running the tests against the polyfill I see the following error:

```
1) Ds\Tests\DequeTest::testEcho
Object of class Ds\Deque could not be converted to string

/Users/dantudor/Sites/php-ds/tests/tests/CollectionTest.php:43
/Users/dantudor/Sites/php-ds/tests/tests/Sequence/_echo.php:8
```

I'm not sure of the purpose of this test as the Collection interface doesn't describe the need for __toString();

**Comment by rtheunissen** [comment]
That's because string representation is handled internally by the extension without the need for `__toString`, which is similar to `unserialize` and `serialize`. I think the best solution is to add those to the interfaces so that the polyfill can implement them.

**Comment by rtheunissen** [comment]
There are other tests that test internal functionality, so we'll need to implement `JsonSerializable`, `ArrayAccess`, `Countable`, and `Iterable`.
