### ISSUE TITLE
Rename the traits to XTrait

### ISSUE THREAD

**Issue by dantudor** [php-ds/polyfill#29]
This will reduce some confusion when seeing two classes both named Collection in such a small codebase.

**Comment by rtheunissen** [comment]
In my opinion (which may or may not be popular), using directories and namespaces correctly removes the need for suffixes. Eg.

`use Traits\Collection;` make it clear that it's a trait in `Traits\`.

The source directory is easy to navigate, unless your editor makes that difficult. I use ST3, can always see the source tree, and simply type Cmd + P + "col" for Collection or Cmd + P + "tr col" for Traits\Collection. I would like to preserve the no-suffix approach until it becomes a problem.

Could argue that it's less confusing in a smaller codebase. :p
