### ISSUE TITLE
Packagist does not contains php-ds polyfill

### ISSUE THREAD

**Issue by SerafimArts** [php-ds/polyfill#32]
Subj: https://packagist.org/packages/php-ds/

Can you add this into packagist?

**Comment by ozanmuyes** [comment]
+1.

So here is a quick work-around;
- Add this repository to your composer.json  
`"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/php-ds/polyfill"
    }
  ],`
- Require php-ds/php-ds  
`"php-ds/php-ds": "dev-master"`
- Here is the catch of this work-around set minimum stability to "dev"  
`"minimum-stability": "dev"`
- Finally update composer dependencies and you're good to go.

**Comment by rtheunissen** [comment]
`composer require php-ds/php-ds` :sparkles:
