### ISSUE TITLE
PHP 5.6

### ISSUE THREAD

**Issue by vondrasekpavel** [php-ds/polyfill#40]
Hi, 

I want use this polyfill in library which needs support php 5.6+. Please how can I do that? 

Thank you for answer.

Pavel

**Comment by rtheunissen** [comment]
This library *requires* 7.0+. Anyone running 5.6 won't be able to use it.

**Comment by vondrasekpavel** [comment]
Yes I understand but in my library I want use your extension for PHP7 users (for performance reasons) and but I need polyfill for 5.6 because I need support this version too :) 

But I think that for 5.6 I can create my own polyfill for back compatibility :) 

Ok, thank you for your extension I like it! :)
