### ISSUE TITLE
Split of Hashable

### ISSUE THREAD

**Issue by johnrobertporter** [php-ds/polyfill#44]
Would it be at all possible to have Hashable split out into a separate repository that doesn't require PHP 7+ ?

I have an old codebase that I want to migrate slowly over to newer concepts, and would like to implement Hashable already, so when I can upgrade the PHP environment, I am already half way there.

Default packages I maintain for the project, like ValueObjects, are already separated out for re-use and were implemented in a newer project running on PHP 7, but out old code can't use these classes as they use Hashable.

**Comment by rtheunissen** [comment]
I see a lot of value in this. There is no reason for Hashable to require PHP 7.0. These classes would still be implemented in the extension, but a composer package for only Hashable makes sense to me. :+1:

**Comment by rtheunissen** [comment]
In hindsight, could you create your own `Hashable` interface in the meantime? It's a bit of a special case and I'm not convinced that it warrants an entire repository to accommodate it.

**Comment by johnrobertporter** [comment]
Thanks for the response. I did do that temporarily, and have since upgraded our platform to PHP 7.2 in all our newer work that would require `Hashable` anyway.

If only these concepts were in the PHP core eh? ;)
