### ISSUE TITLE
Installation instructions improvement

### ISSUE THREAD

**Issue by crocodile2u** [php-ds/polyfill#49]
It is worth mentioning that for those who are sure that the DS extension is loaded but still want polyfill for better IDE autocompletion, _composer require --dev_ is a better option.

**Comment by rtheunissen** [comment]
You can install the polyfill anyway, because it will never be autoloaded (because the classes exist).

**Comment by crocodile2u** [comment]
@rtheunissen , it's never good to bloat production code base with unused code. Makes prod docker images bigger. Not a big deal, but it's also not a big deal to mention this in README
