### ISSUE TITLE
Ds\Map->map() loses keys

### ISSUE THREAD

**Issue by Nebual** [php-ds/polyfill#52]
The polyfill implementation of \Ds\Map->map() loses the keys of the input map, unlike the Extension. I know the polyfill is somewhat-deprecated, and we're switching to the extension, but the incorrectness caught us by surprise.

eg.
```
$map = new \Ds\Map(["speed" => 5, "greatness" => 6]);
$mapped = $map->map(function ($key, $value) {
  return $value * 2;
});
echo $mapped->toArray(); // expected: ["speed" => 10, "greatness" => 12], actual: [10, 12]
```

**Comment by rtheunissen** [comment]
I'll get on this asap, thanks for bringing it up. It shows that we're not testing for that which needs to be corrected.

**Comment by Nebual** [comment]
Opening a PR for both this + the test repo shortly
