### ISSUE TITLE
Install polyfill only

### ISSUE THREAD

**Issue by cup** [php-ds/polyfill#55]
As its currently not possible to install the C extension in some cases, it would
be helpful to be able to install the polyfill only.

If thats already possible, it would be helpful to put instructions on how to do
that.

**Comment by cup** [comment]
https://github.com/php-ds/ext-ds/issues/2

**Comment by rtheunissen** [comment]
You can install just the polyfill with `composer require php-ds/php-ds` as stated in the README.

**Comment by cup** [comment]
Composer is not available on my system - only Pear...
