### ISSUE TITLE
ArrayAccess doesn't provide a way to create references

### ISSUE THREAD

**Issue by rtheunissen** [php-ds/polyfill#7]
`ArrayAccess` doesn't support `$array[][]` syntax, resulting in an `Indirect modification of overloaded element of X has no effect` warning.

This may be a dealbreaker.

**Comment by rtheunissen** [comment]
I don't want to compromise on operator overloading and incomplete array access just to have a polyfill... :sob:

**Comment by dantudor** [comment]
Ouch. This is a problem.

In my mind, the purpose of having a polyfill is aiding people when developing to not have a hard dependency on installing the extension. More importantly I think it will also aid uptake and overall usage of the Data Structures in projects.

Thinking in terms of adoption of the extension, will it be more likely to see adoption with or without a polyfill? Will some of the core PHP libraries/frameworks that are in use today take on a dependency such as DataStructures if that adds a complexity that to install the library you must first install an extension. 

Taking the example of Twig. Would it have been used by Symfony if it could only be installed as an extension?

If sacrificing the ability to overload elements provides greater support for adoption then (in my mind) that would be a worthwhile cost. Unless of course benchmark savings are inadvertently affected.

**Comment by rtheunissen** [comment]
> Thinking in terms of adoption of the extension, will it be more likely to see adoption with or without a polyfill?

Definitely with. No framework or library would depend on it otherwise.

> If sacrificing the ability to overload elements provides greater support for adoption then (in my mind) that would be a worthwhile cost.

I'm okay with no having overloaded operators (&, ^, |, +, - etc) for the sake of having a polyfill. The nested array access limitation not so much. It's a significant setback.

---

Here's my thinking re: adoption. Libraries and frameworks don't have to make use of the extension at all. But the projects you build using those libraries might. Symfony wouldn't, but app X and app Y would.

Maybe one day in the future this becomes part of the default build or demand is enough that it's widely used extension (like xdebug). 

For now I can just see compromise after compromise slicing away at the extension. :cry:

**Comment by rtheunissen** [comment]
I was wrong! :smile_cat: 

See http://chat.stackoverflow.com/transcript/message/28984249#28984249
