### ISSUE TITLE
Method getIterable() does not seem to exist in ext-ds while it does in polyfill

### ISSUE THREAD

**Issue by simPod** [php-ds/polyfill#73]
I've encountered an issue that eg. `Set::getIterator()` is present in polyfill but not in ext-ds. What is intended?

https://github.com/php-ds/polyfill/blob/494494c700f286656154f5617127fd0cbfa60e54/src/Set.php#L411-L416

**Comment by rtheunissen** [comment]
I believe `getIterator` has been implemented in the extension now, as all the collections implement `IteratorAggregate`

**Comment by simPod** [comment]
Aight, I don't really remember what was it about so let's close. I can't come up with any issue I know of currently.
